import React, { useState, useRef, useEffect } from 'react';
import { X, Send, Sparkles, MessageSquare, Image as ImageIcon, Loader2, MessageCircle } from 'lucide-react';
import { createChatSession, sendMessageToGemini, generateImage } from '../utils/gemini';
import { ChatMessage } from '../types';

interface ExtendedMessage extends ChatMessage {
  image?: string;
  isImageRequest?: boolean;
}

export const UniChat: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<ExtendedMessage[]>([
    { role: 'model', text: "안녕하세요! 유니픽셀 AI 디렉터입니다. 영상 제작에 관해 궁금한 점이 있으신가요? '스토리보드 그려줘'라고 말하면 컨셉 이미지를 생성해드립니다." }
  ]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isGeneratingImage, setIsGeneratingImage] = useState(false);
  
  const chatSessionRef = useRef<any>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isOpen && !chatSessionRef.current) {
      chatSessionRef.current = createChatSession();
    }
  }, [isOpen]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim() || !chatSessionRef.current) return;

    const userMsg = input;
    setMessages(prev => [...prev, { role: 'user', text: userMsg }]);
    setInput('');
    setIsTyping(true);

    const isImageIntent = userMsg.includes('그려줘') || userMsg.includes('생성해') || userMsg.includes('이미지') || userMsg.includes('스토리보드');

    if (isImageIntent) {
         setIsTyping(false);
         setIsGeneratingImage(true);
         setMessages(prev => [...prev, { role: 'model', text: `"${userMsg}"에 대한 스토리보드 컨셉을 생성하고 있습니다. (Gemini Nano Banana Model)` }]);
         
         const imageResult = await generateImage(userMsg);
         setIsGeneratingImage(false);

         if (imageResult) {
             setMessages(prev => [...prev, { role: 'model', text: "요청하신 컨셉 이미지입니다.", image: imageResult }]);
         } else {
             setMessages(prev => [...prev, { role: 'model', text: "이미지 생성 중 오류가 발생했습니다. 다시 시도해주세요." }]);
         }
    } else {
        const response = await sendMessageToGemini(chatSessionRef.current, userMsg);
        setMessages(prev => [...prev, { role: 'model', text: response }]);
        setIsTyping(false);
    }
  };

  return (
    <div className="fixed bottom-6 right-6 z-50 flex flex-col items-end font-sans">
      {/* Chat Window */}
      {isOpen && (
        <div className="mb-4 w-80 md:w-96 bg-white rounded-2xl shadow-2xl overflow-hidden border border-gray-100 flex flex-col h-[600px] transition-all duration-300 animate-in slide-in-from-bottom-10 fade-in">
          {/* Header */}
          <div className="bg-slate-900 p-4 flex justify-between items-center text-white">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-gradient-to-tr from-blue-600 to-blue-400 rounded-full flex items-center justify-center shadow-inner">
                 <Sparkles size={20} className="text-white" />
              </div>
              <div>
                <h3 className="font-bold text-sm">Unipixel AI Director</h3>
                <span className="text-[10px] text-blue-300 flex items-center gap-1">
                  <span className="w-1.5 h-1.5 bg-blue-400 rounded-full animate-pulse"></span>
                  Online | Image Gen Available
                </span>
              </div>
            </div>
            <button onClick={() => setIsOpen(false)} className="text-white/60 hover:text-white">
              <X size={20} />
            </button>
          </div>

          {/* Messages */}
          <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-gray-50">
            {messages.map((msg, idx) => (
              <div key={idx} className={`flex flex-col ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
                <div className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-relaxed shadow-sm ${
                  msg.role === 'user' 
                    ? 'bg-blue-600 text-white rounded-tr-none' 
                    : 'bg-white text-gray-800 border border-gray-100 rounded-tl-none'
                }`}>
                  {msg.text}
                </div>
                {msg.image && (
                    <div className="mt-2 rounded-xl overflow-hidden shadow-md max-w-[85%] border-2 border-white">
                        <img src={msg.image} alt="Generated Storyboard" className="w-full h-auto" />
                        <div className="bg-slate-800 text-white text-[10px] px-2 py-1 text-center">
                            Generated by Gemini Nano Banana
                        </div>
                    </div>
                )}
              </div>
            ))}
            
            {isTyping && (
              <div className="flex justify-start">
                <div className="bg-white rounded-2xl rounded-tl-none px-4 py-3 shadow-sm border border-gray-100">
                   <div className="flex gap-1">
                     <span className="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce"></span>
                     <span className="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce delay-75"></span>
                     <span className="w-1.5 h-1.5 bg-gray-400 rounded-full animate-bounce delay-150"></span>
                   </div>
                </div>
              </div>
            )}
            
            {isGeneratingImage && (
                <div className="flex justify-start items-center gap-2 p-2">
                    <Loader2 size={16} className="animate-spin text-blue-600" />
                    <span className="text-xs text-blue-600 font-medium animate-pulse">AI가 이미지를 생성 중입니다...</span>
                </div>
            )}

            <div ref={messagesEndRef} />
          </div>

          {/* Input */}
          <div className="p-3 bg-white border-t border-gray-100">
             {/* Kakao Button Area */}
             <div className="mb-2 px-1">
                 <a href="https://pf.kakao.com/_placeholder" target="_blank" rel="noopener noreferrer" className="w-full bg-[#FEE500] hover:bg-[#FDD835] text-[#3C1E1E] text-xs font-bold py-2 rounded-lg flex items-center justify-center gap-2 transition-colors">
                     <MessageCircle size={14} fill="currentColor"/>
                     카카오톡으로 바로 상담하기
                 </a>
             </div>

             {/* Suggestions */}
             {messages.length < 3 && (
                 <div className="flex gap-2 mb-3 overflow-x-auto pb-1 scrollbar-hide">
                     <button onClick={() => setInput("화장품 광고 영상 스토리보드 그려줘")} className="whitespace-nowrap px-3 py-1 bg-blue-50 text-blue-600 border border-blue-100 rounded-full text-xs hover:bg-blue-100 flex items-center gap-1"><ImageIcon size={10}/> 이미지 생성</button>
                 </div>
             )}
            <div className="relative">
              <input
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSend()}
                placeholder="메시지를 입력하세요..."
                className="w-full bg-gray-100 border-none rounded-full pl-4 pr-12 py-3 text-sm focus:ring-2 focus:ring-blue-500 outline-none transition-all"
              />
              <button 
                onClick={handleSend}
                disabled={!input.trim() || isTyping || isGeneratingImage}
                className="absolute right-2 top-1/2 -translate-y-1/2 p-2 bg-slate-900 text-white rounded-full hover:bg-blue-600 disabled:opacity-50 disabled:hover:bg-slate-900 transition-colors"
              >
                <Send size={14} />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Toggle Button */}
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className={`shadow-2xl flex items-center gap-3 px-6 py-4 rounded-full transition-all duration-300 hover:scale-105 hover:shadow-blue-500/20 ${isOpen ? 'bg-slate-900 text-white' : 'bg-white text-slate-900 border border-gray-100'}`}
      >
        {isOpen ? (
          <>
             <X size={20} />
             <span className="font-bold text-sm">닫기</span>
          </>
        ) : (
          <>
             <div className="relative">
                <MessageSquare size={22} className="text-blue-600" />
                <span className="absolute -top-1 -right-1 flex h-3 w-3">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-3 w-3 bg-blue-500"></span>
                </span>
             </div>
             <div className="flex flex-col items-start">
                 <span className="font-bold text-sm">문의하기</span>
                 <span className="text-[10px] text-gray-400">AI / 카카오톡</span>
             </div>
          </>
        )}
      </button>
    </div>
  );
};